run_modules:
  - c3g_runprocessing
  - c3g_fastp
  - c3g_demuxmetrics
  - c3g_blastresults
  - c3g_verifybamid
  - c3g_alignments
  - c3g_progress  

module_order:
  - c3g_runprocessing
  - c3g_fastp
  - c3g_demuxmetrics
  - c3g_blastresults
  - c3g_verifybamid
  - c3g_alignments
  - c3g_progress

extra_fn_clean_exts:
  - ".fastq"

# read_count_multiplier: 0.000001
read_count_multiplier: 0.001
# read_count_multiplier: 1
read_count_prefix: "k"
yield_multiplier: 0.000001
yield_prefix: "Mb"

log_filesize_limit: 80000000
