run_modules:
  - c3gjobstatus
  - c3galignments
  - demuxmetrics
  - genpipes

# module_order:
#   - c3gjobstatus

extra_fn_clean_exts:
  - ".fastq"

# read_count_multiplier: 0.000001
read_count_multiplier: 0.001
# read_count_multiplier: 1
read_count_prefix: "k"
yield_multiplier: 0.000001
yield_prefix: "Mb"

log_filesize_limit: 80000000
